# docker compose up -d --build --force-recreate
version: '3.8'
name: store

services:

  db:
    container_name: store-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
      - POSTGRES_DB=store
    volumes:
      - $VOLUME/postgres/store/data:/var/lib/postgresql/data
    restart: always
    networks:
      - espm

  account:
    build:
      context: ../poo.241.store.account-service/
      dockerfile: Dockerfile
    image: store-account:latest
    networks:
      - espm

networks:
  espm:
    driver: bridge
